version: "3.8"

services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/__pycache__/
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
    networks:
      - app-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all
    networks:
      - app-network

volumes:
  mongo-data:


networks:
  app-network:
    driver: bridge